import winsound
import time
def noghte():
    winsound.Beep(1000,500)
    print('.')
def khat():
    winsound.Beep(1000,1500)
    print('-')
text=input("Enter Word or number : ").lower()
text_list=list(text)
for i in text_list:
    if i == 'a':
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i =='b':
        khat()
        noghte()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'c':
        khat()
        noghte()
        khat()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'd':
        khat()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'e':
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'f':
        noghte()
        noghte()
        khat()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'g':
        khat()
        khat()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'h':
        noghte()
        noghte()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'i':
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'j':
        noghte()
        khat()
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'k':
        khat()
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'l':
        noghte()
        khat()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'm':
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'n':
        khat()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'o':
        khat()
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'p':
        noghte()
        khat()
        khat()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 'q':
        khat()
        khat()
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'r':
        noghte()
        khat()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 's':
        noghte()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == 't':
        khat()
        print(',')
        time.sleep(1)
    elif i == 'u':
        noghte()
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'v':
        noghte()
        noghte()
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'w':
        noghte()
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'x':
        khat()
        noghte()
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'y':
        khat()
        noghte()
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == 'z':
        khat()
        khat()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == '1':
        noghte()
        khat()
        khat()
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == '2':
        noghte()
        noghte()
        khat()
        khat()
        khat()
        print(',')
        time.sleep(1)

    elif i == '3':
        noghte()
        noghte()
        noghte()
        khat()
        khat()
        print(',')
        time.sleep(1)
    elif i == '4':
        noghte()
        noghte()
        noghte()
        noghte()
        khat()
        print(',')
        time.sleep(1)
    elif i == '5':
        noghte()
        noghte()
        noghte()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == '6':
        khat()
        noghte()
        noghte()
        noghte()
        noghte()
        print(',')
        time.sleep(1)
    elif i == '7':
        khat()
        khat()
        noghte()
        noghte()
        noghte()
        print(',')
        time.sleep(1)

    elif i == '8':
        khat()
        khat()
        khat()
        noghte()
        noghte()
        print(',')
        time.sleep(1)

    elif i == '9':
        khat()
        khat()
        khat()
        khat()
        noghte()
        print(',')
        time.sleep(1)

    elif i == '0':
        khat()
        khat()
        khat()
        khat()
        khat()
        print(',')
        time.sleep(1)
    else:
        print('Wrong Input - Please Enter 1-9 and a-z ')


