import winsound
import time
def dot():
    winsound.Beep(1000,500)
    print('.')
def line():
    winsound.Beep(1000,1500)
    print('-')
text=input("Vared Konid : ").lower()
text_list=list(text)
for i in text_list:
    if i == 'a':
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i =='b':
        line()
        dot()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'c':
        line()
        dot()
        line()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'd':
        line()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'e':
        dot()
        print(',')
        time.sleep(1)
    elif i == 'f':
        dot()
        dot()
        line()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'g':
        line()
        line()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'h':
        dot()
        dot()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'i':
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'j':
        dot()
        line()
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == 'k':
        line()
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i == 'l':
        dot()
        line()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'm':
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == 'n':
        line()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'o':
        line()
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == 'p':
        dot()
        line()
        line()
        dot()
        print(',')
        time.sleep(1)
    elif i == 'q':
        line()
        line()
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i == 'r':
        dot()
        line()
        dot()
        print(',')
        time.sleep(1)
    elif i == 's':
        dot()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == 't':
        line()
        print(',')
        time.sleep(1)
    elif i == 'u':
        dot()
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i == 'v':
        dot()
        dot()
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i == 'w':
        dot()
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == 'x':
        line()
        dot()
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i == 'y':
        line()
        dot()
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == 'z':
        line()
        line()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == '1':
        dot()
        line()
        line()
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == '2':
        dot()
        dot()
        line()
        line()
        line()
        print(',')
        time.sleep(1)

    elif i == '3':
        dot()
        dot()
        dot()
        line()
        line()
        print(',')
        time.sleep(1)
    elif i == '4':
        dot()
        dot()
        dot()
        dot()
        line()
        print(',')
        time.sleep(1)
    elif i == '5':
        dot()
        dot()
        dot()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == '6':
        line()
        dot()
        dot()
        dot()
        dot()
        print(',')
        time.sleep(1)
    elif i == '7':
        line()
        line()
        dot()
        dot()
        dot()
        print(',')
        time.sleep(1)

    elif i == '8':
        line()
        line()
        line()
        dot()
        dot()
        print(',')
        time.sleep(1)

    elif i == '9':
        line()
        line()
        line()
        line()
        dot()
        print(',')
        time.sleep(1)

    elif i == '0':
        line()
        line()
        line()
        line()
        line()
        print(',')
        time.sleep(1)
    else:
        print('Voroodi eshtebah ast - bayad bein 1-9 va a-z bashad')


